#! /usr/bin/bash -x
#
# Turn on the services need to push/pull data to/from shore, but not the local sync
#
# June-2021, Pat Welch, pat@mousebrains.com

SERVICES="syncPush syncPull"
sudo systemctl enable $SERVICES
sudo systemctl restart $SERVICES
