#! /usr/bin/bash -x
#
# Turn on the services to push/pull data to/from shore and to the local backup machine
#
# June-2021, Pat Welch, pat@mousebrains.com

SERVICES="syncPush syncPull syncLocal Trigger positionHarvester"
sudo systemctl enable $SERVICES
sudo systemctl restart $SERVICES
